---
- name: AWS - Criando Instancias
  hosts: localhost
  tasks:
    - name: Criando - Security Group 
      ec2_group:
        name: webserver
        description: Regras de Firewall - DevSecOps
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: <change-me>

    - name: Criando SSH PAIR
      ec2_key:
        name: devsecops
        key_material: '<change-me>'

    - name: Criando Instancia EC2
      ec2:
        key_name: devsecops
        instance_type: t2.micro
        region: us-east-1
        image: ami-5a809b25
        wait: yes
        group: webserver
        count: 1
        user_data: |
          #!/bin/bash
          sudo apt-get update
          sudo apt-get install nginx -y
          echo "AWS - DevSecOps" > /var/www/html/index.html
